name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "
        cd /opt/bar-app &&
        git fetch origin main &&
        git reset --hard origin/main &&
        source venv/bin/activate &&
        sudo venv/bin/python3 -m pip install -r requirements.txt
        "

    - name: Restart Flask development server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "
        cd /opt/bar-app &&
        source venv/bin/activate &&
        pkill -f 'flask run' &&
        nohup flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
        "
        
